#!/usr/bin/env bash
# =============================================================================
# Rebuild and redeploy Sub2API from local source code.
#
# Default persistent root:
#   /opt/proxy/sub2api
#
# Persisted host-side files/directories:
#   $DEPLOY_ROOT/.env                 deployment env/secrets
#   $DEPLOY_ROOT/data/config.yaml     app config generated by AUTO_SETUP
#   $DEPLOY_ROOT/data/.installed      install lock
#   $DEPLOY_ROOT/data/logs/           app logs
#   $DEPLOY_ROOT/postgres_data/       PostgreSQL data
#   $DEPLOY_ROOT/redis_data/          Redis data
#   $NGINX_ROOT/conf.d/               Nginx reverse-proxy config
#   $NGINX_ROOT/html/                 Nginx static/ACME challenge webroot
#   $NGINX_ROOT/logs/                 Nginx logs
#   $NGINX_ROOT/cache/                Nginx cache/temp data
#   $NGINX_ROOT/certs/                Future SSL certificates/keys
#
# Typical usage after modifying code:
#   ./deploy/redeploy-proxy.sh
#
# Optional examples:
#   ./deploy/redeploy-proxy.sh --no-cache
#   DEPLOY_ROOT=/opt/proxy/sub2api ./deploy/redeploy-proxy.sh
# =============================================================================

set -Eeuo pipefail

DEFAULT_DEPLOY_ROOT="/opt/proxy/sub2api"
DEFAULT_NGINX_ROOT="/opt/proxy/nginx"
DEPLOY_ROOT="${DEPLOY_ROOT:-$DEFAULT_DEPLOY_ROOT}"
NGINX_ROOT="${NGINX_ROOT:-$DEFAULT_NGINX_ROOT}"
PROJECT_NAME="${PROJECT_NAME:-sub2api}"
SUB2API_IMAGE="${SUB2API_IMAGE:-sub2api:build-server}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-240}"
WAIT_INTERVAL="${WAIT_INTERVAL:-5}"

NO_CACHE=0
PULL_BASE_IMAGES=0
RESTART_ALL=0
SKIP_HEALTH=0
INIT_ONLY=0

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
COMPOSE_FILE="${COMPOSE_FILE:-$SCRIPT_DIR/docker-compose.proxy.yml}"
ENV_FILE="${ENV_FILE:-$DEPLOY_ROOT/.env}"
ENV_EXAMPLE="${ENV_EXAMPLE:-$SCRIPT_DIR/.env.example}"
APP_CONFIG_FILE="$DEPLOY_ROOT/data/config.yaml"
INSTALL_LOCK_FILE="$DEPLOY_ROOT/data/.installed"
NGINX_CONF_FILE="$NGINX_ROOT/conf.d/sub2api.conf"

usage() {
  cat <<'EOF'
Usage:
  deploy/redeploy-proxy.sh [options]

Options:
  --no-cache       Rebuild the Sub2API image without Docker build cache.
  --pull-base      Pull newer base images while building.
  --restart-all    Recreate all Compose services, not only the app container.
  --skip-health    Skip post-deploy health checks.
  --init-only      Only create /opt/proxy/sub2api directories and .env, then exit.
  -h, --help       Show this help.

Environment variables:
  DEPLOY_ROOT      Persistent root directory. Default: /opt/proxy/sub2api
  NGINX_ROOT       Nginx config/data/certs root. Default: /opt/proxy/nginx
  PROJECT_NAME     Docker Compose project name. Default: sub2api
  SUB2API_IMAGE    Local image tag. Default: sub2api:build-server
  COMPOSE_FILE     Compose file path. Default: deploy/docker-compose.proxy.yml
  ENV_FILE         Env file path. Default: $DEPLOY_ROOT/.env
  HEALTH_TIMEOUT   Health wait timeout in seconds. Default: 240

Persisted configuration:
  $DEPLOY_ROOT/.env              Compose env and fixed secrets.
  $DEPLOY_ROOT/data/config.yaml  App config generated on first successful AUTO_SETUP.
  $NGINX_ROOT/conf.d/sub2api.conf Nginx reverse-proxy config for Sub2API.
  $NGINX_ROOT/html/.well-known/acme-challenge  HTTP-01 challenge webroot.
  $NGINX_ROOT/certs              Future SSL certificate/key files.
  Do not pre-create config.yaml: its presence tells Sub2API setup is already done.
EOF
}

while (($#)); do
  case "$1" in
    --no-cache)
      NO_CACHE=1
      ;;
    --pull-base)
      PULL_BASE_IMAGES=1
      ;;
    --restart-all)
      RESTART_ALL=1
      ;;
    --skip-health)
      SKIP_HEALTH=1
      ;;
    --init-only)
      INIT_ONLY=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

export DEPLOY_ROOT ENV_FILE PROJECT_NAME SUB2API_IMAGE NGINX_ROOT

log() {
  printf '[INFO] %s\n' "$*"
}

warn() {
  printf '[WARN] %s\n' "$*" >&2
}

fail() {
  printf '[ERROR] %s\n' "$*" >&2
  exit 1
}

on_error() {
  local exit_code=$?
  local line_no=${1:-unknown}
  printf '[ERROR] Failed at line %s with exit code %s\n' "$line_no" "$exit_code" >&2
  printf '[ERROR] Last logs: docker compose --env-file %q -f %q -p %q logs --tail=120 sub2api\n' "$ENV_FILE" "$COMPOSE_FILE" "$PROJECT_NAME" >&2
  exit "$exit_code"
}
trap 'on_error $LINENO' ERR

need_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

create_dir() {
  local dir="$1"
  if [[ -d "$dir" ]]; then
    return 0
  fi
  if mkdir -p "$dir" 2>/dev/null; then
    return 0
  fi
  if command -v sudo >/dev/null 2>&1; then
    sudo install -d -m 755 -o "$(id -un)" -g "$(id -gn)" "$dir"
    return 0
  fi
  fail "Cannot create directory: $dir"
}

chmod_path() {
  local mode="$1"
  local path="$2"
  if chmod "$mode" "$path" 2>/dev/null; then
    return 0
  fi
  if command -v sudo >/dev/null 2>&1; then
    sudo chmod "$mode" "$path"
    return 0
  fi
  fail "Cannot chmod $mode: $path"
}

ensure_prerequisites() {
  need_command docker
  need_command python3
  docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin is unavailable: docker compose version failed"
  [[ -f "$COMPOSE_FILE" ]] || fail "Compose file not found: $COMPOSE_FILE"
  [[ -f "$ENV_EXAMPLE" ]] || fail "Env example not found: $ENV_EXAMPLE"
}

ensure_deploy_root() {
  create_dir "$DEPLOY_ROOT"
  create_dir "$DEPLOY_ROOT/data"
  create_dir "$DEPLOY_ROOT/postgres_data"
  create_dir "$DEPLOY_ROOT/redis_data"
  create_dir "$DEPLOY_ROOT/backups"
}

ensure_nginx_root() {
  create_dir "$NGINX_ROOT"
  create_dir "$NGINX_ROOT/conf.d"
  create_dir "$NGINX_ROOT/html"
  create_dir "$NGINX_ROOT/html/.well-known"
  create_dir "$NGINX_ROOT/html/.well-known/acme-challenge"
  create_dir "$NGINX_ROOT/logs"
  create_dir "$NGINX_ROOT/cache"
  create_dir "$NGINX_ROOT/certs"
  chmod_path 700 "$NGINX_ROOT/certs"

  local default_cert="$NGINX_ROOT/certs/default-selfsigned.crt"
  local default_key="$NGINX_ROOT/certs/default-selfsigned.key"
  if [[ ! -f "$default_cert" || ! -f "$default_key" ]]; then
    need_command openssl
    log "Creating default self-signed nginx TLS certificate: $default_cert"
    rm -f "$default_cert.tmp" "$default_key.tmp"
    openssl req \
      -x509 \
      -nodes \
      -newkey rsa:2048 \
      -days 3650 \
      -subj "/CN=sub2api.local" \
      -keyout "$default_key.tmp" \
      -out "$default_cert.tmp" >/dev/null 2>&1
    chmod_path 600 "$default_key.tmp"
    chmod_path 644 "$default_cert.tmp"
    mv "$default_key.tmp" "$default_key"
    mv "$default_cert.tmp" "$default_cert"
  fi
  chmod_path 600 "$default_key"
  chmod_path 644 "$default_cert"

  if [[ ! -f "$NGINX_CONF_FILE" ]]; then
    log "Creating default nginx proxy config: $NGINX_CONF_FILE"
    python3 - "$NGINX_CONF_FILE" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
path.write_text(r'''# Managed default for Sub2API reverse proxy.
# Edit this file on the host, then reload nginx:
#   docker compose --env-file /opt/proxy/sub2api/.env -f deploy/docker-compose.proxy.yml -p sub2api exec nginx nginx -s reload
#
# A default self-signed certificate is generated under /opt/proxy/nginx/certs
# so port 443 is active immediately. Replace these files with real certificates
# later, then reload nginx.

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/sub2api.access.log;
    error_log /var/log/nginx/sub2api.error.log warn;

    client_max_body_size 256m;

    # Webroot for ACME/Let's Encrypt HTTP-01 challenges.
    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://sub2api:8080;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        # WebSocket / streaming support.
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 900s;
        proxy_send_timeout 900s;
        proxy_buffering off;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name _;

    ssl_certificate /etc/nginx/certs/default-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/default-selfsigned.key;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    access_log /var/log/nginx/sub2api.ssl.access.log;
    error_log /var/log/nginx/sub2api.ssl.error.log warn;

    client_max_body_size 256m;

    location / {
        proxy_pass http://sub2api:8080;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;

        # WebSocket / streaming support.
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 900s;
        proxy_send_timeout 900s;
        proxy_buffering off;
    }
}

# For a real domain certificate, either replace the default-selfsigned files
# above or edit ssl_certificate / ssl_certificate_key to point at files you
# place under /opt/proxy/nginx/certs.
''')
PY
    chmod 644 "$NGINX_CONF_FILE"
  fi
}

ensure_env_file() {
  local created=0
  if [[ ! -f "$ENV_FILE" ]]; then
    log "Creating env file: $ENV_FILE"
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    created=1
  fi

  local env_update_status
  env_update_status="$(python3 - "$ENV_FILE" <<'PY'
from pathlib import Path
import secrets
import sys

path = Path(sys.argv[1])
text = path.read_text()
keys = {
    "POSTGRES_PASSWORD": {"", "change_this_secure_password"},
    "JWT_SECRET": {""},
    "TOTP_ENCRYPTION_KEY": {""},
}
seen = set()
changed = False
out = []
for line in text.splitlines():
    replaced = False
    if line and not line.lstrip().startswith("#") and "=" in line:
        key, value = line.split("=", 1)
        key = key.strip()
        if key in keys:
            seen.add(key)
            if value.strip() in keys[key]:
                out.append(f"{key}={secrets.token_hex(32)}")
                changed = True
                replaced = True
    if not replaced:
        out.append(line)

for key in keys:
    if key not in seen:
        out.append(f"{key}={secrets.token_hex(32)}")
        changed = True

new_text = "\n".join(out) + "\n"
if new_text != text:
    path.write_text(new_text)
    changed = True

print("updated" if changed else "unchanged")
PY
)"

  chmod 600 "$ENV_FILE"
  if [[ "$env_update_status" == "updated" ]]; then
    log "Ensured required secrets in $ENV_FILE; values are hidden."
  fi
  if [[ "$created" == "1" ]]; then
    warn "Generated $ENV_FILE with secure secrets. Values are not printed."
    warn "Review ADMIN_EMAIL, ADMIN_PASSWORD, BIND_HOST, SERVER_PORT, TZ and OAuth settings before production exposure."
  fi
}

compose() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" -p "$PROJECT_NAME" "$@"
}

check_container_ownership() {
  local name project
  for name in sub2api sub2api-postgres sub2api-redis sub2api-nginx; do
    if docker ps -a --format '{{.Names}}' | grep -Fxq "$name"; then
      project="$(docker inspect -f '{{ index .Config.Labels "com.docker.compose.project" }}' "$name" 2>/dev/null || true)"
      if [[ -n "$project" && "$project" != "$PROJECT_NAME" ]]; then
        fail "Container $name already exists under compose project '$project', expected '$PROJECT_NAME'. Stop and review before overwriting."
      fi
      if [[ -z "$project" ]]; then
        fail "Container $name already exists but is not labeled as a Docker Compose container. Stop and review before overwriting."
      fi
    fi
  done
}

set_build_metadata() {
  cd "$REPO_ROOT"
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    BUILD_COMMIT="$(git rev-parse --short HEAD)"
    if [[ -n "$(git status --porcelain)" ]]; then
      BUILD_COMMIT="${BUILD_COMMIT}-dirty"
    fi
  else
    BUILD_COMMIT="local"
  fi
  BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  export BUILD_COMMIT BUILD_DATE
  log "Build metadata: COMMIT=$BUILD_COMMIT DATE=$BUILD_DATE IMAGE=$SUB2API_IMAGE"
}

render_config() {
  log "Validating Compose config"
  compose config >/dev/null
}

build_image() {
  local build_flags=()
  if [[ "$NO_CACHE" == "1" ]]; then
    build_flags+=(--no-cache)
  fi
  if [[ "$PULL_BASE_IMAGES" == "1" ]]; then
    build_flags+=(--pull)
  fi

  cd "$REPO_ROOT"
  log "Building Sub2API image from local source"
  compose build "${build_flags[@]}" sub2api
}

update_containers() {
  cd "$REPO_ROOT"
  if [[ "$RESTART_ALL" == "1" ]]; then
    log "Starting/recreating all services"
    compose up -d --force-recreate
  else
    log "Ensuring PostgreSQL and Redis are running"
    compose up -d postgres redis
    log "Recreating Sub2API app container with the freshly built image"
    compose up -d --force-recreate --no-deps sub2api
    log "Ensuring Nginx reverse proxy is running"
    compose up -d --force-recreate --no-deps nginx
  fi
}

container_health() {
  local name="$1"
  docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$name" 2>/dev/null || printf 'missing'
}

wait_for_health() {
  local deadline=$((SECONDS + HEALTH_TIMEOUT))
  local app pg redis nginx

  log "Waiting for containers to become healthy, timeout=${HEALTH_TIMEOUT}s"
  while (( SECONDS < deadline )); do
    app="$(container_health sub2api)"
    pg="$(container_health sub2api-postgres)"
    redis="$(container_health sub2api-redis)"
    nginx="$(container_health sub2api-nginx)"
    if [[ "$app" == "healthy" && "$pg" == "healthy" && "$redis" == "healthy" && "$nginx" == "healthy" ]]; then
      log "All containers are healthy"
      return 0
    fi
    printf '[INFO] health: sub2api=%s postgres=%s redis=%s nginx=%s\n' "$app" "$pg" "$redis" "$nginx"
    sleep "$WAIT_INTERVAL"
  done

  compose ps || true
  warn "Health check timed out. App logs may contain credentials; inspect them manually only in a trusted shell if needed."
  fail "Health check timed out"
}

post_deploy_checks() {
  log "Running service probes"
  compose exec -T postgres pg_isready >/dev/null
  compose exec -T redis sh -c 'if [ -n "${REDIS_PASSWORD:-}" ]; then REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli ping >/dev/null; else env -u REDISCLI_AUTH redis-cli ping >/dev/null; fi'
  compose exec -T sub2api wget -q -T 5 -O /dev/null http://localhost:8080/health
  compose exec -T nginx nginx -t >/dev/null
  compose exec -T nginx wget -q -T 5 -O /dev/null http://127.0.0.1/health

  log "Current service status"
  compose ps

  log "Persistent mounts"
  docker inspect sub2api --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}'
  docker inspect sub2api-postgres --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}'
  docker inspect sub2api-redis --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}'
  docker inspect sub2api-nginx --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}'

  log "Persistent configuration files"
  printf '[INFO] env file: %s\n' "$ENV_FILE"
  printf '[INFO] nginx config: %s\n' "$NGINX_CONF_FILE"
  printf '[INFO] nginx certs: %s\n' "$NGINX_ROOT/certs"
  printf '[INFO] nginx ACME webroot: %s\n' "$NGINX_ROOT/html/.well-known/acme-challenge"
  if [[ -f "$APP_CONFIG_FILE" ]]; then
    printf '[INFO] app config: %s\n' "$APP_CONFIG_FILE"
  else
    warn "App config not found yet: $APP_CONFIG_FILE"
    warn "It should be generated on first successful AUTO_SETUP. Do not pre-create it, because config.yaml presence skips first-run setup."
  fi
  if [[ -f "$INSTALL_LOCK_FILE" ]]; then
    printf '[INFO] install lock: %s\n' "$INSTALL_LOCK_FILE"
  fi
}

main() {
  ensure_prerequisites
  ensure_deploy_root
  ensure_nginx_root
  ensure_env_file

  log "Deploy root: $DEPLOY_ROOT"
  log "Nginx root: $NGINX_ROOT"
  log "Env file: $ENV_FILE"
  log "App config file: $APP_CONFIG_FILE"
  log "Nginx config: $NGINX_CONF_FILE"
  log "Compose file: $COMPOSE_FILE"

  if [[ "$INIT_ONLY" == "1" ]]; then
    log "Initialization complete. Edit $ENV_FILE if needed, then rerun without --init-only."
    exit 0
  fi

  check_container_ownership
  set_build_metadata
  render_config
  build_image
  update_containers

  if [[ "$SKIP_HEALTH" == "1" ]]; then
    warn "Skipped health checks by request."
    compose ps
  else
    wait_for_health
    post_deploy_checks
  fi

  log "Redeploy complete. Data root: $DEPLOY_ROOT; Nginx root: $NGINX_ROOT"
  warn "If ADMIN_PASSWORD was left empty, Sub2API may generate an initial admin password. Retrieve it only from a trusted local shell and do not paste it into shared logs."
}

main "$@"
